BEGIN;
ALTER TABLE "search_legalresource_tags" DROP CONSTRAINT "legalresource_id_refs_id_36b9bb23";
DROP TABLE "search_legalresource";
DROP TABLE "search_legalresource_tags";
ALTER TABLE "search_employmentresource_tags" DROP CONSTRAINT "employmentresource_id_refs_id_78884fbb";
DROP TABLE "search_employmentresource";
DROP TABLE "search_employmentresource_tags";
ALTER TABLE "search_communityresource_tags" DROP CONSTRAINT "communityresource_id_refs_id_241c0aa9";
DROP TABLE "search_communityresource";
DROP TABLE "search_communityresource_tags";
ALTER TABLE "search_housingresource_tags" DROP CONSTRAINT "housingresource_id_refs_id_7c002e95";
DROP TABLE "search_housingresource";
DROP TABLE "search_housingresource_tags";
DROP TABLE "search_legaltag";
DROP TABLE "search_employmenttag";
DROP TABLE "search_communitytag";
DROP TABLE "search_housingtag";
DROP TABLE "reviews_review";
DROP TABLE "django_admin_log";
DROP TABLE "django_site";
DROP TABLE "django_session";
ALTER TABLE "auth_user_user_permissions" DROP CONSTRAINT "user_id_refs_id_f2045483";
ALTER TABLE "auth_user_groups" DROP CONSTRAINT "user_id_refs_id_831107f1";
DROP TABLE "auth_user";
DROP TABLE "auth_user_user_permissions";
DROP TABLE "auth_user_groups";
ALTER TABLE "auth_group_permissions" DROP CONSTRAINT "group_id_refs_id_3cea63fe";
DROP TABLE "auth_group";
DROP TABLE "auth_group_permissions";
DROP TABLE "auth_permission";
DROP TABLE "django_content_type";

COMMIT;
